modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "holdcam"
version = "${version}"
displayName = "HoldCam"
authors = "yuko1101"
description = '''
Provides keybindings for 3rd person view while holding.
'''
#logoFile = ""

[[dependencies.holdcam]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.holdcam]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "holdcam.mixins.json"
